// components/constants.js
import { StyleSheet, Platform } from 'react-native';

export const UNIFIED_STYLES = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f5f5f5',
        alignItems: 'center',
        justifyContent: 'center',
        // paddingLeft: 30,
        // paddingRight: 30,
        paddingTop: 16,
    },

    container2: {
        flex: 1,
        width: '95%',
        maxWidth: 900,
        alignSelf: 'center',
        marginTop: 16,
    },
    title: {
        fontFamily: Platform.OS === 'ios' ? 'System' : 'monospace',
        fontSize: 22,
        fontWeight: 'bold',
        marginBottom: 12,
        color: '#000000',
        textShadowColor: '#fff',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 0,
        paddingHorizontal: 16,
        paddingVertical: 6,
        alignSelf: 'stretch',
        textAlign: 'center',
    },
    buttonRow: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        position: 'sticky',
        left: 0,
        right: 0,
        bottom: 0,
        width: '100%',
        gap: 16,
        padding: 16,
        backgroundColor: '#f5f5f5', // опціонально, щоб не зливалося з фоном
    },
    input: {
        backgroundColor: '#fff',
        borderWidth: 2,
        borderColor: '#b0b0b0',
        borderRadius: 0,
        padding: 6,
        marginBottom: 4,
        fontFamily: 'System',
        fontSize: 15,
        color: '#222',
        shadowColor: '#fff',
        shadowOffset: { width: 1, height: 1 },
        shadowOpacity: 1,
        shadowRadius: 0,
        maxWidth: 400,
    },
});